title: Tech terms for NOOBS!
author: lpoon22
email: screwdriverp@gmail.com
description:: > 
  My attempt at documenting my learnings as I skill myself up!

permalink: /:title/

#build settings
theme: minima
plugins:

